CREATE DATABASE `SCOTT` DEFAULT CHARACTER SET utf8mb4;

USE SCOTT;

CREATE TABLE IF NOT EXISTS `BONUS`(
`ENAME` varchar(10) DEFAULT NULL,
`JOB` varchar(9) DEFAULT NULL,
`SAL` double DEFAULT NULL,
`COMM` double DEFAULT NULL);

drop table IF EXISTS depts;

CREATE TABLE IF NOT EXISTS `DEPT`(
`DEPTNO` int(11) NOT NULL,
`DNAME` varchar(14) DEFAULT NULL,
`COC` varchar(13) DEFAULT NULL,
PRIMARY KEY (`DEPTNO`));

INSERT INTO `DEPT` (`DEPTNO`, `DNAME`, `COC`)
VALUES (10, 'ACCOUNTING', 'NEW YORK'), (20, 'RESERCH', 'DALLAS'),(30, 'SALES', 'CHICAGO'), (40, 'OPERATIONS', 'BOSTON');

CREATE TABLE IF NOT EXISTS `EMP`(
`EMPNO` int(11) NOT NULL,
`ENAME` varchar(10) DEFAULT NULL,
`JOB` varchar(9) DEFAULT NULL,
`MGR` int(11) DEFAULT NULL,
`SAL` double DEFAULT NULL,
`COMM` double DEFAULT NULL,
`DEPTNO` int(11) DEFAULT NULL,
PRIMARY KEY (`EMPNO`),
KEY `PK_EMP` (`DEPTNO`));

INSERT INTO `EMP`
VALUES (1, 'KING2', 'PRESIDENT', NULL, 5000, NULL, 20),
(2, 'CLARK2', 'MANAGER', 1, 2450, NULL, 20),
(3, 'MILLER2', 'CLERK', 2, 1300, NULL, 20);

SHOW TABLES;
DESC emp;

SELECT concat('회장님의 이름은? ', ename)
FROM emp 
WHERE job = 'PRESIDENT';
SELECT 
	JOB AS '직업', COUNT(*) 사원수, SUM(SAL) 급여총액, AVG(SAL) 평균급여
FROM 
	EMP
GROUP BY job;